name: Deploy to Raspberry Pi

on:
  push:
    branches:
      - main  # Adjust this to match your branch name

jobs:
  deploy:
    runs-on: self-hosted
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: SSH into Raspberry Pi and deploy
      uses: appleboy/ssh-action@master
      with:
        host: youri
        username: youri
        key: b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAABlwAAAAdzc2gtcn
NhAAAAAwEAAQAAAYEA1flj173oF7fQZygNv12IgHz4n6MGz3nI3yb+Vr5OeKAqgPxmX2xf
o68u1ZLuxDHVPZLMWMiX16dB/KM5SGCIKK5JCSCsVTqq2MfHOUW69vP4t/LFAzAn+9SSFS
UGYIa0DQZ2UmJk+oC//fgtr/tgQ6TRjhwzRkn4FDDrGiT8aTtqBC0/LaRX+QjFHVPjk/Tm
2nwHpkzFUi9ADP6EbhmXtFG4TJhz7XF/rAYfB8tZrLmladZPhXSIj+5WQjLG163vSz/LVZ
pZKduxlsfwT1wtsx/FjrjCEmyqPYr6glnAeuqWHYD3MX4ZnfqQQ+nEDSynA+VVGiumReqh
ZpdfYmq9vuvL3gZHMVOhqKuYJp0X1xslJ+Ru3SHFHX7nhqik5IsH9LFQZ1HQInztX0FNoM
lCoNjxl8mSzzA9UYCI97Vd4gP7YnuCMIWo7ATtyAEeQlO2eET7sLzg1FUdPDURAhlAybTW
ttTaCEGR45Ll/bdSpF/GxFJX6it5pPVn6oYyk5nFAAAFiLYyPlC2Mj5QAAAAB3NzaC1yc2
EAAAGBANX5Y9e96Be30GcoDb9diIB8+J+jBs95yN8m/la+TnigKoD8Zl9sX6OvLtWS7sQx
1T2SzFjIl9enQfyjOUhgiCiuSQkgrFU6qtjHxzlFuvbz+LfyxQMwJ/vUkhUlBmCGtA0Gdl
JiZPqAv/34La/7YEOk0Y4cM0ZJ+BQw6xok/Gk7agQtPy2kV/kIxR1T45P05tp8B6ZMxVIv
QAz+hG4Zl7RRuEyYc+1xf6wGHwfLWay5pWnWT4V0iI/uVkIyxtet70s/y1WaWSnbsZbH8E
9cLbMfxY64whJsqj2K+oJZwHrqlh2A9zF+GZ36kEPpxA0spwPlVRorpkXqoWaXX2Jqvb7r
y94GRzFToairmCadF9cbJSfkbt0hxR1+54aopOSLB/SxUGdR0CJ87V9BTaDJQqDY8ZfJks
8wPVGAiPe1XeID+2J7gjCFqOwE7cgBHkJTtnhE+7C84NRVHTw1EQIZQMm01rbU2ghBkeOS
5f23UqRfxsRSV+oreaT1Z+qGMpOZxQAAAAMBAAEAAAGBAItAuXyfR9ufsc5gn8nJuls8ea
WSuIzwCg1IWD/lrDYOrnqxSIKTig6BpO4zqJYghFGFJt4k9cTQQj6Dj3UN9a7b9gYtsFnr
S2K3aW1ZdxreniBAq3yuq2bV6Zg/N048fBL6AKkPBf6NKeXDzR/5baW4LvTYX3pAC2ZAi9
DA/1AQ7ab4N2ShzurwjS/P94zD1jWcgHH3Bne87mdGgLMSjss4X8Phd5iww9EVTr6I1bx2
OTOO2MPWmkVpa9O7LfMRazemE4hSH11G6suNvnzn26DHIxYnMCfAwfOuT/E1ou1Fst9AoZ
cu6FlPo2lcH7aR5ZRkXeBpLVfYgasuLAXEmPLgoc4CNlGhj3xoBV+DjuBl6sleaelYtwo+
3Uo1SdMU8GvIw74/wirk4eXtRKHlyzlhydtrd8qGiuhVh5PPYVcjP/4Q9Pb3A52TrFZoBr
IU8vPoOXBmTgacxNmiPP/GPEEg3kmb2AMmbGxqM+UUSidCKHWjYcPjlYwKU2aICaIN4QAA
AMBXad02wKlrylRoDVmyLpdJlCTaRHcDdrb4GftmPsUQr/OzNdi5UGvjZPylp9ZpL5vTEd
So5Lm5l/6YMd0awpYy7F8mP4Kqn5HEOrrG3Qe6z5TgjLB/eLHoLdwfCI2ktlozG00zFPty
6Xw72+VT7uIucKuJWuE/F87xE1zfp3gMJxu72p2pn76jvRMqyd3sthaqBTenNOrockLtvW
bAA5yd992JOqNR+TFL4u2I/4pYHs9WXbG9Y3uZnO3Fi/73Q9oAAADBAP2NmuDlY31X86to
YUvG2vD//V/m6upeAmHp07tIlRe4JshPRPvnDdLWLxLkqqSh8jMr80Co0+3mWos0d26OBz
3yvHuc/v/yETK7+jenGLdpGNWuul12PD+16ihAyK7t/TV/bR2T2+rBRqSZd9aOx3X/2hni
/PJWQawfJfZhEQl808cCkDTJDRv25lrmWvhX1lMksrb6dU44fgIbkpXIbyOVR6t7m3z11d
eB92NSQz5uXRO2X5lyWQzTCaONAypK7QAAAMEA2AoBpfgSe2itcMfxVpRm2AcQ0d+4wXM5
cdtpP7bB6UtkJR0LIhLpDSwkZSnyQ4pjJcmnD/mF0Mm3WJ4GzFuhltp7E/+Uy0EcFAHK/S
Bk0DvKpjivvYsDKuDEadYgYVdGfQsg4fFg3BQ9MxOq19tdDBlA/uwR9VOUPBrqV0HRiI6a
SJUSRpKGEbYPrDi2lnK2hs+YaTpY9aVfmF0ZT1XtOIpRRdVS+05tFUaYjD2O6WhM2bs3DH
nbAD/OcoE2UDc5AAAAC3lvdXJpQHlvdXJpAQIDBAUGBw==
        port: 22
        script: |
          cd "/home/youri/testBot/"
          git pull origin main
          # Add any additional steps to start your application here
